"""Refresh the self-contained CAD Viewer controls from current A0 datums."""
import json
from pathlib import Path
import layout_model as m
HERE=Path(__file__).parent
parts=m.build_parts(catalog=False)
names=[n for n,d in parts.items() if d['owner'] in ['M019a','M021a']]
manifest=dict(schemaVersion=1,step={'path':'head/layout-02/head-layout.step'},parameters={
 'roll_deg':dict(type='number',label='Roll',unit='°',min=-18,max=18,step=1,default=0,description='Viewer pose about the derived roll axis; does not regenerate STEP.'),
 'pitch_deg':dict(type='number',label='Pitch',unit='°',min=-22,max=40,step=1,default=0),
 'yaw_deg':dict(type='number',label='Yaw',unit='°',min=-55,max=55,step=1,default=0,description='Body and cable swept clearance are not modeled.'),
 'show_shell':dict(type='boolean',label='Show shell and ear caps',default=True,description='Hide exterior skins and visible screws to inspect the mechanism.')},
 features={'rolling':{'ref':'#o1.1'},'pitch_carried':{'ref':'#o1.2'},'yaw_carried':{'ref':'#o1.3'},'covers':{'names':names}})
code='// Generated by write_viewer_params.py. Viewer poses only; geometry stays 1:1.\n'
code+='const axes = '+json.dumps(m.AXES)+';\n'
code+='const clamp = (n,a,b) => Math.min(b,Math.max(a,Number(n)||0));\n'
code+='export default {\n  manifest: '+json.dumps(manifest,indent=2)+',\n'
code+='''  update({params,effects}) {
    const roll={rotate:{axis:[1,0,0],origin:[0,axes.roll_y,axes.roll_z],angleDeg:clamp(params.roll_deg,-18,18)}};
    const pitch={rotate:{axis:[0,1,0],origin:[axes.pitch_x,0,axes.pitch_z],angleDeg:clamp(params.pitch_deg,-22,40)}};
    const yaw={rotate:{axis:[0,0,1],origin:[axes.pitch_x,0,-60],angleDeg:clamp(params.yaw_deg,-55,55)}};
    effects.transform('rolling',{transforms:[roll,pitch,yaw]});
    effects.transform('pitch_carried',{transforms:[pitch,yaw]});
    effects.transform('yaw_carried',yaw);
    effects.visible('covers',params.show_shell!==false);
  }
};
'''
(HERE/'head-layout.params.js').write_text(code)
print('Wrote motion controls from',m.AXES)
