/* Generated by generate.py from schema.json. Exploratory layout; not registered. */
#ifndef RP02_PHASE_A_CODEC_H
#define RP02_PHASE_A_CODEC_H
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define RP02_LAYOUT_REVISION 1u
#define RP02_MAX_PAYLOAD 64u
#define RP02_HEADER_SIZE 33u
#define RP02_MAX_RAW (RP02_HEADER_SIZE + RP02_MAX_PAYLOAD + 2u)
#define RP02_MAX_WIRE (RP02_MAX_RAW + 2u)

enum rp02_message_type {
    RP02_HELLO = 1,
    RP02_LIMITS_SET = 2,
    RP02_HEAD_ENABLE = 3,
    RP02_HEAD_INHIBIT = 4,
    RP02_HEAD_GOAL = 5,
    RP02_HEAD_CANCEL = 6,
    RP02_FACE_STATE = 7,
    RP02_LIGHT_STATE = 8,
    RP02_HEAD_STATE = 9,
    RP02_HEARTBEAT = 10,
    RP02_FAULT = 11,
    RP02_ACK = 12,
    RP02_NACK = 13,
    RP02_TIME_SYNC_REQ = 14,
    RP02_TIME_SYNC_RESP = 15,
};

typedef struct {
    uint8_t type;
    uint16_t seq;
    uint8_t boot_uuid[16];
    uint32_t epoch;
    uint64_t src_ts_us;
    uint8_t payload_len;
    uint8_t payload[RP02_MAX_PAYLOAD];
} rp02_frame;

static inline uint16_t rp02_crc16(const uint8_t *p, size_t n) {
    uint16_t crc = 0xffffu;
    for (size_t i = 0; i < n; ++i) {
        crc ^= (uint16_t)p[i] << 8;
        for (unsigned b = 0; b < 8; ++b)
            crc = (crc & 0x8000u) ? (uint16_t)((crc << 1) ^ 0x1021u) : (uint16_t)(crc << 1);
    }
    return crc;
}
static inline void rp02_put(uint8_t *p, uint64_t v, unsigned n) {
    for (unsigned i = 0; i < n; ++i) p[i] = (uint8_t)(v >> (8u * i));
}
static inline uint64_t rp02_get(const uint8_t *p, unsigned n) {
    uint64_t v = 0;
    for (unsigned i = 0; i < n; ++i) v |= (uint64_t)p[i] << (8u * i);
    return v;
}
static inline int rp02_encode(const rp02_frame *f, uint8_t *wire, size_t cap, size_t *used) {
    if (!f || !wire || !used || f->payload_len > RP02_MAX_PAYLOAD || cap < RP02_MAX_WIRE) return -1;
    uint8_t raw[RP02_MAX_RAW];
    raw[0] = RP02_LAYOUT_REVISION; raw[1] = f->type;
    rp02_put(raw + 2, f->seq, 2); memcpy(raw + 4, f->boot_uuid, 16);
    rp02_put(raw + 20, f->epoch, 4); rp02_put(raw + 24, f->src_ts_us, 8);
    raw[32] = f->payload_len; memcpy(raw + 33, f->payload, f->payload_len);
    size_t n = 33u + f->payload_len;
    rp02_put(raw + n, rp02_crc16(raw, n), 2); n += 2;
    size_t out = 0, code_pos = out++, code = 1;
    for (size_t i = 0; i < n; ++i) {
        if (raw[i] == 0 || code == 0xffu) {
            wire[code_pos] = (uint8_t)code; code_pos = out++; code = 1;
            if (raw[i] == 0) continue;
        }
        wire[out++] = raw[i]; ++code;
    }
    wire[code_pos] = (uint8_t)code; wire[out++] = 0; *used = out;
    return 0;
}
static inline int rp02_decode(const uint8_t *wire, size_t n, rp02_frame *f) {
    if (!wire || !f || n < 2 || n > RP02_MAX_WIRE || wire[n-1] != 0) return -1;
    uint8_t raw[RP02_MAX_RAW]; size_t at = 0, out = 0;
    while (at < n - 1) {
        uint8_t code = wire[at++]; if (!code || at + code - 1 > n - 1) return -2;
        if (out + code > RP02_MAX_RAW + 1u) return -2;
        for (unsigned i = 1; i < code; ++i) raw[out++] = wire[at++];
        if (code != 0xffu && at < n - 1) {
            if (out == RP02_MAX_RAW) return -2;
            raw[out++] = 0;
        }
    }
    if (out < 35 || raw[0] != RP02_LAYOUT_REVISION || raw[32] > RP02_MAX_PAYLOAD || out != 35u + raw[32]) return -3;
    if (rp02_crc16(raw, out - 2) != rp02_get(raw + out - 2, 2)) return -4;
    f->type = raw[1]; f->seq = (uint16_t)rp02_get(raw + 2, 2);
    memcpy(f->boot_uuid, raw + 4, 16); f->epoch = (uint32_t)rp02_get(raw + 20, 4);
    f->src_ts_us = rp02_get(raw + 24, 8); f->payload_len = raw[32];
    memcpy(f->payload, raw + 33, f->payload_len); return 0;
}
#endif
