# Generated by generate.py from schema.json. Exploratory layout; not registered.
from __future__ import annotations
from enum import IntEnum
from dataclasses import dataclass
import struct

LAYOUT_REVISION = 1
MAX_PAYLOAD = 64
HEADER = struct.Struct("<BBH16sIQB")

class MessageType(IntEnum):
    HELLO = 1
    LIMITS_SET = 2
    HEAD_ENABLE = 3
    HEAD_INHIBIT = 4
    HEAD_GOAL = 5
    HEAD_CANCEL = 6
    FACE_STATE = 7
    LIGHT_STATE = 8
    HEAD_STATE = 9
    HEARTBEAT = 10
    FAULT = 11
    ACK = 12
    NACK = 13
    TIME_SYNC_REQ = 14
    TIME_SYNC_RESP = 15

@dataclass(frozen=True)
class Frame:
    kind: MessageType
    seq: int
    boot_uuid: bytes
    epoch: int
    src_ts_us: int
    payload: bytes = b""

def crc16(data: bytes) -> int:
    crc = 0xffff
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xffff if crc & 0x8000 else (crc << 1) & 0xffff
    return crc

def cobs_encode(data: bytes) -> bytes:
    out = bytearray(b"\x00")
    code_index = 0
    code = 1
    for byte in data:
        if byte == 0 or code == 0xff:
            out[code_index] = code
            code_index = len(out)
            out.append(0)
            code = 1
            if byte == 0:
                continue
        out.append(byte)
        code += 1
    out[code_index] = code
    return bytes(out)

def cobs_decode(data: bytes) -> bytes:
    out = bytearray()
    at = 0
    while at < len(data):
        code = data[at]
        if code == 0 or at + code > len(data) + 1:
            raise ValueError("invalid COBS")
        at += 1
        end = at + code - 1
        if end > len(data):
            raise ValueError("truncated COBS")
        out.extend(data[at:end])
        at = end
        if code != 0xff and at < len(data):
            out.append(0)
    return bytes(out)

def encode(frame: Frame) -> bytes:
    if len(frame.boot_uuid) != 16 or len(frame.payload) > MAX_PAYLOAD:
        raise ValueError("invalid boot UUID or payload size")
    raw = HEADER.pack(LAYOUT_REVISION, frame.kind, frame.seq, frame.boot_uuid,
                      frame.epoch, frame.src_ts_us, len(frame.payload)) + frame.payload
    raw += struct.pack("<H", crc16(raw))
    return cobs_encode(raw) + b"\x00"

def decode(wire: bytes) -> Frame:
    if not wire.endswith(b"\x00") or wire == b"\x00":
        raise ValueError("missing frame delimiter")
    raw = cobs_decode(wire[:-1])
    if len(raw) < HEADER.size + 2:
        raise ValueError("short frame")
    body, got_crc = raw[:-2], struct.unpack("<H", raw[-2:])[0]
    if crc16(body) != got_crc:
        raise ValueError("bad CRC")
    rev, kind, seq, boot, epoch, stamp, size = HEADER.unpack_from(body)
    if rev != LAYOUT_REVISION or size > MAX_PAYLOAD or len(body) != HEADER.size + size:
        raise ValueError("layout or length mismatch")
    return Frame(MessageType(kind), seq, boot, epoch, stamp, body[HEADER.size:])
