"""Generate the exploratory C0 Python and C2 C frame codecs from schema.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
schema = json.loads((ROOT / "schema.json").read_text())
assert schema["status"] == "EXP_ONLY_NOT_REGISTERED"
assert schema["endianness"] == "little"
assert schema["crc"] == "CRC-16/CCITT-FALSE"
assert schema["framing"] == "COBS plus 0x00 delimiter"
assert schema["max_payload"] == 64
assert schema["header"] == [
    ["layout_revision", "u8"], ["type", "u8"], ["seq", "u16"],
    ["boot_uuid", "bytes16"], ["epoch", "u32"], ["src_ts_us", "u64"],
    ["payload_len", "u8"],
]

messages = schema["messages"]
assert len(set(messages.values())) == len(messages)
py_ids = "\n".join(f"    {name} = {value}" for name, value in messages.items())
c_ids = "\n".join(f"    RP02_{name} = {value}," for name, value in messages.items())

py = '''# Generated by generate.py from schema.json. Exploratory layout; not registered.
from __future__ import annotations
from enum import IntEnum
from dataclasses import dataclass
import struct

LAYOUT_REVISION = 1
MAX_PAYLOAD = 64
HEADER = struct.Struct("<BBH16sIQB")

class MessageType(IntEnum):
__PY_IDS__

@dataclass(frozen=True)
class Frame:
    kind: MessageType
    seq: int
    boot_uuid: bytes
    epoch: int
    src_ts_us: int
    payload: bytes = b""

def crc16(data: bytes) -> int:
    crc = 0xffff
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xffff if crc & 0x8000 else (crc << 1) & 0xffff
    return crc

def cobs_encode(data: bytes) -> bytes:
    out = bytearray(b"\\x00")
    code_index = 0
    code = 1
    for byte in data:
        if byte == 0 or code == 0xff:
            out[code_index] = code
            code_index = len(out)
            out.append(0)
            code = 1
            if byte == 0:
                continue
        out.append(byte)
        code += 1
    out[code_index] = code
    return bytes(out)

def cobs_decode(data: bytes) -> bytes:
    out = bytearray()
    at = 0
    while at < len(data):
        code = data[at]
        if code == 0 or at + code > len(data) + 1:
            raise ValueError("invalid COBS")
        at += 1
        end = at + code - 1
        if end > len(data):
            raise ValueError("truncated COBS")
        out.extend(data[at:end])
        at = end
        if code != 0xff and at < len(data):
            out.append(0)
    return bytes(out)

def encode(frame: Frame) -> bytes:
    if len(frame.boot_uuid) != 16 or len(frame.payload) > MAX_PAYLOAD:
        raise ValueError("invalid boot UUID or payload size")
    raw = HEADER.pack(LAYOUT_REVISION, frame.kind, frame.seq, frame.boot_uuid,
                      frame.epoch, frame.src_ts_us, len(frame.payload)) + frame.payload
    raw += struct.pack("<H", crc16(raw))
    return cobs_encode(raw) + b"\\x00"

def decode(wire: bytes) -> Frame:
    if not wire.endswith(b"\\x00") or wire == b"\\x00":
        raise ValueError("missing frame delimiter")
    raw = cobs_decode(wire[:-1])
    if len(raw) < HEADER.size + 2:
        raise ValueError("short frame")
    body, got_crc = raw[:-2], struct.unpack("<H", raw[-2:])[0]
    if crc16(body) != got_crc:
        raise ValueError("bad CRC")
    rev, kind, seq, boot, epoch, stamp, size = HEADER.unpack_from(body)
    if rev != LAYOUT_REVISION or size > MAX_PAYLOAD or len(body) != HEADER.size + size:
        raise ValueError("layout or length mismatch")
    return Frame(MessageType(kind), seq, boot, epoch, stamp, body[HEADER.size:])
'''.replace("__PY_IDS__", py_ids)

c = '''/* Generated by generate.py from schema.json. Exploratory layout; not registered. */
#ifndef RP02_PHASE_A_CODEC_H
#define RP02_PHASE_A_CODEC_H
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define RP02_LAYOUT_REVISION 1u
#define RP02_MAX_PAYLOAD 64u
#define RP02_HEADER_SIZE 33u
#define RP02_MAX_RAW (RP02_HEADER_SIZE + RP02_MAX_PAYLOAD + 2u)
#define RP02_MAX_WIRE (RP02_MAX_RAW + 2u)

enum rp02_message_type {
__C_IDS__
};

typedef struct {
    uint8_t type;
    uint16_t seq;
    uint8_t boot_uuid[16];
    uint32_t epoch;
    uint64_t src_ts_us;
    uint8_t payload_len;
    uint8_t payload[RP02_MAX_PAYLOAD];
} rp02_frame;

static inline uint16_t rp02_crc16(const uint8_t *p, size_t n) {
    uint16_t crc = 0xffffu;
    for (size_t i = 0; i < n; ++i) {
        crc ^= (uint16_t)p[i] << 8;
        for (unsigned b = 0; b < 8; ++b)
            crc = (crc & 0x8000u) ? (uint16_t)((crc << 1) ^ 0x1021u) : (uint16_t)(crc << 1);
    }
    return crc;
}
static inline void rp02_put(uint8_t *p, uint64_t v, unsigned n) {
    for (unsigned i = 0; i < n; ++i) p[i] = (uint8_t)(v >> (8u * i));
}
static inline uint64_t rp02_get(const uint8_t *p, unsigned n) {
    uint64_t v = 0;
    for (unsigned i = 0; i < n; ++i) v |= (uint64_t)p[i] << (8u * i);
    return v;
}
static inline int rp02_encode(const rp02_frame *f, uint8_t *wire, size_t cap, size_t *used) {
    if (!f || !wire || !used || f->payload_len > RP02_MAX_PAYLOAD || cap < RP02_MAX_WIRE) return -1;
    uint8_t raw[RP02_MAX_RAW];
    raw[0] = RP02_LAYOUT_REVISION; raw[1] = f->type;
    rp02_put(raw + 2, f->seq, 2); memcpy(raw + 4, f->boot_uuid, 16);
    rp02_put(raw + 20, f->epoch, 4); rp02_put(raw + 24, f->src_ts_us, 8);
    raw[32] = f->payload_len; memcpy(raw + 33, f->payload, f->payload_len);
    size_t n = 33u + f->payload_len;
    rp02_put(raw + n, rp02_crc16(raw, n), 2); n += 2;
    size_t out = 0, code_pos = out++, code = 1;
    for (size_t i = 0; i < n; ++i) {
        if (raw[i] == 0 || code == 0xffu) {
            wire[code_pos] = (uint8_t)code; code_pos = out++; code = 1;
            if (raw[i] == 0) continue;
        }
        wire[out++] = raw[i]; ++code;
    }
    wire[code_pos] = (uint8_t)code; wire[out++] = 0; *used = out;
    return 0;
}
static inline int rp02_decode(const uint8_t *wire, size_t n, rp02_frame *f) {
    if (!wire || !f || n < 2 || n > RP02_MAX_WIRE || wire[n-1] != 0) return -1;
    uint8_t raw[RP02_MAX_RAW]; size_t at = 0, out = 0;
    while (at < n - 1) {
        uint8_t code = wire[at++]; if (!code || at + code - 1 > n - 1) return -2;
        if (out + code > RP02_MAX_RAW + 1u) return -2;
        for (unsigned i = 1; i < code; ++i) raw[out++] = wire[at++];
        if (code != 0xffu && at < n - 1) {
            if (out == RP02_MAX_RAW) return -2;
            raw[out++] = 0;
        }
    }
    if (out < 35 || raw[0] != RP02_LAYOUT_REVISION || raw[32] > RP02_MAX_PAYLOAD || out != 35u + raw[32]) return -3;
    if (rp02_crc16(raw, out - 2) != rp02_get(raw + out - 2, 2)) return -4;
    f->type = raw[1]; f->seq = (uint16_t)rp02_get(raw + 2, 2);
    memcpy(f->boot_uuid, raw + 4, 16); f->epoch = (uint32_t)rp02_get(raw + 20, 4);
    f->src_ts_us = rp02_get(raw + 24, 8); f->payload_len = raw[32];
    memcpy(f->payload, raw + 33, f->payload_len); return 0;
}
#endif
'''.replace("__C_IDS__", c_ids)

(ROOT / "codec.py").write_text(py)
(ROOT / "codec.h").write_text(c)
